### Week 6 Numpy Practice Problems (continued)

In [5]:
import numpy as np

### Problem 1
Use numpy to create a function that adds a border filled with zeros around an existing array.

*Hint*: Use numpy's `pad` function. See https://numpy.org/doc/stable/reference/generated/numpy.pad.html

Note: we did not cover this function in class, see if you are comfortable of reading numpy documents and learn on your own!

In [8]:
def add_border(x):
    return np.pad(x, pad_width=1, mode='constant', constant_values=0)

In [9]:
x = np.ones((1, 1))
claimed = add_border(x)
correct = np.zeros((3, 3))
correct[1, 1] = 1.0
assert claimed.shape == correct.shape
assert np.all(np.abs(claimed - correct) < 1e-8)

In [10]:
# Let's go throught the document together
# The np.pad function in NumPy is versatile and can be used in various ways to add borders or padding to arrays
# 1) Number of values padded to the edges of each axis. ((before_1, after_1), ... (before_N, after_N)) 
x = np.array([[1, 2], [3, 4]])
padded = np.pad(x, pad_width=((1,2), (2,1)), mode='constant', constant_values=0)
print(padded)

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 0 3 4 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [11]:
# Pad with different mode 'constant' -> 'mode'
x = np.array([[1, 2], [3, 4]])
padded = np.pad(x, pad_width=((1,2), (2,1)), mode='edge')
print(padded)

[[1 1 1 2 2]
 [1 1 1 2 2]
 [3 3 3 4 4]
 [3 3 3 4 4]
 [3 3 3 4 4]]


In [12]:
# Pad with different values on each side
x = np.array([[1, 2], [3, 4]])
padded = np.pad(x, pad_width=((1,2), (2,1)), mode='constant', constant_values=((5,6), (7,8)))
print(padded)

[[7 7 5 5 8]
 [7 7 1 2 8]
 [7 7 3 4 8]
 [7 7 6 6 8]
 [7 7 6 6 8]]


### Problem 2
Create an $n \times n$ numpy array filled with a checkerboard pattern of zeros and ones. The first entry should be the integer `0`. Assume $n \ge 2$.

In [6]:
def make_checkerboard(n):
    checkerboard = np.zeros((n, n), dtype=int)
    
    #every odd row and every even column
    checkerboard[1::2, ::2] = 1
    #every even row and every odd column
    checkerboard[::2, 1::2] = 1
    
    return checkerboard

In [7]:
correct = \
    [[0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0]]
assert np.all(correct == make_checkerboard(8))

### Problem 3
Your task is to create a 2D array that shows the temperature for each city for each day of the week, assuming all cities have the same temperature pattern but with different baselines:

City 1: (first in the list): Use the temperatures as they are

City 2: Add  `5°C` to the temperatures

City 3: Subtract  `2°C` from the temperatures

In [32]:
def create_city_temperatures(temperatures, cities, offsets=None):
    temperatures = np.array(temperatures)

    city_1 = temperatures
    city_2 = temperatures + 5
    city_3 = temperatures - 2


    temperature_array = np.vstack([city_1, city_2, city_3])
    
    return temperature_array

In [33]:
# Given data
temperatures = np.array([20, 22, 25, 19, 23, 21, 18])  # 7 days
cities = np.array(['New York', 'Los Angeles', 'Chicago'])
# Create and print the result
result = create_city_temperatures(temperatures, cities)
print(result)
# Print with city names
for i, city in enumerate(cities):
    print(f"\n{city}:")
    #print(result[:, i])
    print(result[i])

[[20 22 25 19 23 21 18]
 [25 27 30 24 28 26 23]
 [18 20 23 17 21 19 16]]

New York:
[20 22 25 19 23 21 18]

Los Angeles:
[25 27 30 24 28 26 23]

Chicago:
[18 20 23 17 21 19 16]


In [ ]:
temps_reshaped = temperatures[:, np.newaxis]

if offsets is None:
    